### ISSUE TITLE
Sandbox violation when installing gsl

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#507] opened 2018-06-10 20:02 UTC
Not sure when this started. It is not a sage-on-gentoo issue, per se; I'm only looking for confirmation before going to the science overlay guys. Unless I've done something stupid the issue is with `alternatives-2.eclass` from the science overlay. No overlay version of `gsl` will install here.
```
libtool: install: /usr/lib/portage/python2.7/ebuild-helpers/xattr/install -c .libs/gsl-histogram /var/tmp/portage/sci-libs/gsl-2.4/image//usr/bin/gsl-histogram
make[2]: Leaving directory '/var/tmp/portage/sci-libs/gsl-2.4/work/gsl-2.4-abi_x86_64.amd64'
make[1]: Leaving directory '/var/tmp/portage/sci-libs/gsl-2.4/work/gsl-2.4-abi_x86_64.amd64'
 ^[[31;01m*^[[0m ^[[31;01mACCESS DENIED^[[0m:  mkdir:        /etc/env.d/alternatives/cblas/gsl
mkdir: cannot create directory ‘/etc/env.d/alternatives/cblas/gsl’: Permission denied
^[[31m^[[1m!!! Error: ^[(B^[[mFailed to create /etc/env.d/alternatives/cblas/gsl
Call stack:
    * alternatives_do_add (alternatives-common.bash:288)
    * do_add (alternatives.eselect:147)
    * check_do (core.bash:24)
    * do_action (core.bash:105)
    * main (eselect:311)
exiting
 ^[[31;01m*^[[0m ERROR: sci-libs/gsl-2.4::science failed (install phase):
 ^[[31;01m*^[[0m   (no error message)
 ^[[31;01m*^[[0m
 ^[[31;01m*^[[0m Call stack:
 ^[[31;01m*^[[0m     ebuild.sh, line  124:  Called src_install
 ^[[31;01m*^[[0m   environment, line 3217:  Called alternatives_for 'cblas' 'gsl' '0' '/usr/lib64/pkgconfig/cblas.pc' 'gslcblas.pc' '/usr/include/cblas.h' 'gsl/gsl_cblas.h'
 ^[[31;01m*^[[0m   environment, line  572:  Called die
 ^[[31;01m*^[[0m The specific snippet of code:
 ^[[31;01m*^[[0m       ALTERNATIVESDIR_ROOT="${D%/}" eselect alternatives add ${@} || die;
 ^[[31;01m*^[[0m
 ^[[31;01m*^[[0m If you need support, post the output of `emerge --info '=sci-libs/gsl-2.4::science'`,
 ^[[31;01m*^[[0m the complete build log and the output of `emerge -pqv '=sci-libs/gsl-2.4::science'`.
 ^[[31;01m*^[[0m The complete build log is located at '/var/tmp/portage/sci-libs/gsl-2.4/temp/build.log'.
 ^[[31;01m*^[[0m The ebuild environment file is located at '/var/tmp/portage/sci-libs/gsl-2.4/temp/environment'.
 ^[[31;01m*^[[0m Working directory: '/var/tmp/portage/sci-libs/gsl-2.4/work/gsl-2.4'
 ^[[31;01m*^[[0m S: '/var/tmp/portage/sci-libs/gsl-2.4/work/gsl-2.4'
 ^[[31;01m*^[[0m --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 ^[[31;01m*^[[0m LOG FILE: "/var/log/sandbox/sandbox-17493.log"
 ^[[31;01m*^[[0m
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: mkdir
S: deny
P: gsl
A: /etc/env.d/alternatives/cblas/gsl
R: /etc/env.d/alternatives/cblas/gsl
C: mkdir -p /etc/env.d/alternatives/cblas/gsl
```
And then also some QA
```
QA Notice: Unrecognized configure options:

        --without-cblas-external
        --without-cblas-external
```

**Comment by kiwifb** [comment] 2018-06-10 21:01
There was an update to eselect in the science overlay over the week end. Could be related. I will check at the first opportunity.

**Comment by kiwifb** [comment] 2018-06-10 21:11
Cannot reproduce here, everything went smoothly. I get the QA warning though.

**Comment by kiwifb** [comment] 2018-06-10 22:36
Right, I should have thought about it straight away. I am using `USE=cblas-external` which is why I didn't see it. With that flag no alternative is installed. I think https://github.com/gentoo/sci/commit/d39b8890d1ed73efb2035a5b2689d3cb7c72fcb5#diff-04c5b6fa0785c60578917545f40e7160R566 is at fault. Just my intuition at this stage but we are missing a prefix. This probably affect other blas/cblas/lapack providers may pay to check bugzilla.

**Comment by kiwifb** [comment] 2018-06-10 22:42
Didn't get a sandbox violation with openblas but it is failing before getting to the sandbox violation because a file already exist. I am fairly sure we should have a sandbox violation instead. In any case I am fairly sure eselect is broken _and_ the eclass has been updated to require the broken version.

**Comment by kiwifb** [comment] 2018-06-10 22:45
But I can reproduce the sandbox violation with `blas-reference` which I didn't have installed on the system before
```
-- Installing: /dev/shm/portage/sci-libs/blas-reference-20161223-r100/image/usr/lib64/librefblas.so
make: Leaving directory '/dev/shm/portage/sci-libs/blas-reference-20161223-r100/work/lapack-3.7.0-abi_x86_64.amd64_int32/BLAS'
 * abi_x86_64.amd64_int32: running numeric-int64-multibuild_multilib_wrapper pc_file blas reference
 * int32: running numeric-int64-multibuild_multilib_wrapper pc_install blas reference
 * ACCESS DENIED:  mkdir:        /etc/env.d/alternatives/blas/reference
mkdir: cannot create directory ‘/etc/env.d/alternatives/blas/reference’: Permission denied
!!! Error: Failed to create /etc/env.d/alternatives/blas/reference
Call stack:
    * alternatives_do_add (alternatives-common.bash:288)
    * do_add (alternatives.eselect:147)
    * check_do (core.bash:24)
    * do_action (core.bash:105)
    * main (eselect:311)
exiting
 * ERROR: sci-libs/blas-reference-20161223-r100::science failed (install phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_install
 *   environment, line 4790:  Called numeric-int64-multibuild_install_alternative 'blas' 'reference'
 *   environment, line 3552:  Called numeric-int64-multibuild_foreach_int_abi 'pc_install' 'blas' 'reference'
 *   environment, line 3521:  Called multibuild_foreach_variant 'numeric-int64-multibuild_multilib_wrapper' 'pc_install' 'blas' 'reference'
 *   environment, line 3030:  Called _multibuild_run 'numeric-int64-multibuild_multilib_wrapper' 'pc_install' 'blas' 'reference'
 *   environment, line 3028:  Called numeric-int64-multibuild_multilib_wrapper 'pc_install' 'blas' 'reference'
 *   environment, line 3571:  Called pc_install 'blas' 'reference'
 *   environment, line 3548:  Called alternatives_for 'blas' 'reference' '0' '/usr/lib64/pkgconfig/blas.pc' 'refblas.pc'
 *   environment, line 1078:  Called die
 * The specific snippet of code:
 *       ALTERNATIVESDIR_ROOT="${D%/}" eselect alternatives add ${@} || die;
```

**Comment by kiwifb** [comment] 2018-06-10 22:54
Mu hunch is wrong. Someone will have to dive in the elect code again to find out where a `${D}` or an `${ED}` is missing. Not looking forward to it - been there done that before.

**Comment by strogdon** [comment] 2018-06-11 00:48
Good! When I sync'd yesterday it had been nearly 2 months? My timing was just right.

**Comment by kiwifb** [comment] 2018-06-13 05:15
I finished investigating this. Closing.

**Closed by kiwifb** 2018-06-13 05:15 UTC
