### ISSUE TITLE
chatter when installing sage-doc-9999 on Prefix

### ISSUE THREAD

**Issue by strogdon** [cschwan/sage-on-gentoo#660] opened 2021-11-13 04:31 UTC
I believe this was present prior to `sage-doc` and seems to be innocuous, but I'm unable to find the source. I see output like the following after the install:
```
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/jupyter/kernels/sagemath/doc: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/pdf/en/reference/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/fr/tutorial/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/fr/a_tour_of_sage/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/prep/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/developer/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/reference/matrices/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/reference/repl/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/reference/riemannian_geometry/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/reference/stats/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/reference/structure/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/reference/tensor_free_modules/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/reference/hyperbolic_geometry/_static: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/gentoo-rap/usr/share/doc/sage-doc-9999/html/en/reference/plotting/_static: Is a directory
...
```
Any idea about the source?

**Comment by kiwifb** [comment] 2021-11-13 04:38
I see why this looks strange, I don't use `grep`. What is just before those messages?

**Comment by strogdon** [comment] 2021-11-13 04:42
The `jobserver` stuff
```
 *      make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
 *      make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
 *      make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/g
entoo-rap/usr/share/jupyter/kernels/sagemath/doc: Is a directory
grep: /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image/storage/strogdon/g
entoo-rap/usr/share/doc/sage-doc-9999/pdf/en/reference/_static: Is a directory
```
and prior to that
```
>>> Install sci-mathematics/sage-doc-9999 into /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathemati
cs/sage-doc-9999/image
/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work /storage/strogdon/gentoo-
rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999
/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999
>>> Completed installing sci-mathematics/sage-doc-9999 into /storage/strogdon/gentoo-rap/var/tmp/portage/
sci-mathematics/sage-doc-9999/image

 * Final size of build directory: 2858900 KiB (  2.7 GiB)
 * Final size of installed tree:   469516 KiB (458.5 MiB)

 * QA Notice: make jobserver unavailable:
```

**Comment by kiwifb** [comment] 2021-11-13 06:39
I forgot about the `jobserver` stuff, I can do something for that I think. The `grep` thing may come from portage itself, I'll have to check sage_docbuild but the `grep` invocation feels indirect.

**Comment by strogdon** [comment] 2021-11-13 06:42
I couldn't find where `grep` was being called - portage may be the culprit.

**Comment by kiwifb** [comment] 2021-11-13 06:44
You only see that on prefix?

**Comment by strogdon** [comment] 2021-11-13 06:47
yes

**Comment by kiwifb** [comment] 2021-11-13 06:49
I feel very much like pointing my finger to `usr/lib/portage/python3.9/install-qa-check.d/05prefix`, the next question is why now.

**Comment by strogdon** [comment] 2021-11-13 06:52
I believe the issue has been present for some time. I just ignored it since the install seemed to be correct.

**Comment by kiwifb** [comment] 2021-11-13 06:58
There are 2 lines with a grep call in the file I mentioned. My gut feeling is that it is caused by the first one which checks for files that are not properly prefixed, but I am not sure what is the trigger because I am not sure how it works.

**Comment by strogdon** [comment] 2021-11-13 07:06
Maybe related to using relative symlinks?

**Comment by kiwifb** [comment] 2021-11-13 07:13
Maybe, in fact thinking more about it, it is more likely the second `grep`. A `find` command feeds a list of files to `grep` to check for "shebang", if a folder is caught by the find command I am expecting that message.
```
        # this is hell expensive, but how else?
        find "${ED}" -executable \! -type d -print0 \
                        | xargs -0 grep -H -n -m1 "^#!" \
                        | while read f ;
```
your comment on symlinks is in fact insightful, the executable check looks for "x" which folders and symlinked folders have, but `-type d` fails to recognise it as a folder because it is a symlink. I think it is an interesting bug in portage prefix.

**Comment by kiwifb** [comment] 2021-11-13 07:21
Reading the `find` manpage, I am convinced that it is the issue. It is fixable by writing the command slightly differently. May be `find "${ED}" -L -executable \! -xtype d -print0 \`.

**Comment by strogdon** [comment] 2021-11-13 08:25
Interesting, adding the `-L` gives no `grep`s but terminates with
```
 *      make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
find: unknown predicate `-L'
```

**Comment by kiwifb** [comment] 2021-11-13 08:29
Probably put it in the wrong place, it is not an option I am in the habit of using. `find -L "${ED}"` is probably the right syntax.

**Comment by kiwifb** [comment] 2021-11-13 09:48
Cannot fix the `jobserver` so far. If that's a problem the `sphinx` generated stuff it may be hard to fix at all.

**Comment by strogdon** [comment] 2021-11-13 17:58
This seems to be the thing to do
```
        # this is hell expensive, but how else?
        find -L "${ED}" -executable \! -type d -print0 \
```
No `grep`s
```
>>> Install sci-mathematics/sage-doc-9999 into /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image
/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999
/storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/work/sage-doc-9999
>>> Completed installing sci-mathematics/sage-doc-9999 into /storage/strogdon/gentoo-rap/var/tmp/portage/sci-mathematics/sage-doc-9999/image

 * Final size of build directory: 2858792 KiB (  2.7 GiB)
 * Final size of installed tree:   469488 KiB (458.4 MiB)

 * QA Notice: make jobserver unavailable:
 * 
 *      make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
 *      make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
 ```

**Comment by strogdon** [comment] 2021-11-16 02:17
On Sat, 13 Nov 2021 01:48:34 -0800
François Bissey ***@***.***> wrote:

> Cannot fix the `jobserver` so far. If that's a problem the `sphinx`
> generated stuff it may be hard to fix at all.
> 

I think the `sphinx` generated stuff is the cause of the `jobserver`
warnings. I've tried every `standard` trick to accommodate the
suggestion - `Add '+' to parent make rule` without success.

**Comment by kiwifb** [comment] 2021-11-16 06:34
That's exactly my experience and why I am potentially incriminating `sphinx`.

**Comment by strogdon** [comment] 2021-11-17 03:31
When doing `make doc-pdf` on vanilla (building did not complete since I do not have all available `l10n_LANGS` installed) I see numerous
```
make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```
as well as
```
make[3]: warning: -j9 forced in submake: resetting jobserver mode.
```
and  latex related warnings
```
(/usr/share/texmf-dist/tex/latex/tools/array.stymake[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
(/usr/share/texmf-dist/tex/latex/letltxmacro/letltxmacro.stymake[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
(/usr/share/texmf-dist/tex/latex/titlesec/titlesec.sty) [89make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
(/usr/share/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty]make[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
(/usr/share/texmf-dist/tex/latex/capt-of/capt-of.stymake[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
(/usr/share/texmf-dist/tex/latex/hyperref/hyperref-langpatches.defmake[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
(/usr/share/texmf-dist/tex/latex/url/url.stymake[4]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
```

**Comment by kiwifb** [comment] 2021-11-17 03:55
This is very strange as I don't have any `.stymake` files, and of course the files I have do not look like makefiles at all. I should have a squeeze at my build logs.

**Comment by kiwifb** [comment] 2021-11-17 03:58
Nothing nearly as interesting in my logs.

**Comment by kiwifb** [comment] 2021-11-17 04:01
Top hit from google for "sphinx make jobserver" https://lore.kernel.org/lkml/20191121205929.40371-4-keescook@chromium.org/

**Comment by kiwifb** [comment] 2021-11-17 04:07
That one has a bit more in terms of explanations http://lkml.iu.edu/hypermail/linux/kernel/1909.2/03880.html still we are talking 2019. Inspecting sage_docbuild for interesting stuff.

**Comment by strogdon** [comment] 2021-11-17 04:07
Interesting!

To get the above, from vanilla home I removed `logs/docpdf.log` and then after `make docpdf` I have a new `logs/docpdf.log` with the above.

**Comment by kiwifb** [comment] 2021-11-17 09:09
Tried to edit sphinx's provided Makefiles but no use.

**Comment by kiwifb** [comment] 2021-11-17 09:57
I had a feeling but trying `emake -j1 doc-pdf` confirmed it, building pdf doc rebuilds part of the html documentation, even if you have already done it before, because of https://github.com/sagemath/sage/blob/develop/src/doc/Makefile#L69. And at `-j1`, that's really slow. It may pay to try to build both html and pdf in the same make invocation.

**Comment by kiwifb** [comment] 2021-11-17 20:02
Still cannot fix `jobserver` but I have seriously reduced some install time. On my computer:
* html only: 8 minutes and 51 seconds.
* html+pdf (original): 17 minutes and 18 seconds.
* html+pdf (new): 12 minutes and 7 seconds.

**Comment by kiwifb** [comment] 2021-11-19 01:05
Improvements from the vbraun branch are now merged in master for 9.5.beta7.

**Comment by kiwifb** [comment] 2021-11-23 20:51
Did you ever fill a bug against prefix for the original chatter?

**Comment by strogdon** [comment] 2021-11-24 00:34
No I didn't. I should do that.

**Comment by strogdon** [comment] 2021-11-24 02:38
See https://bugs.gentoo.org/826986 in case I didn't adequately describe the issue.

**Comment by strogdon** [comment] 2021-11-24 05:03
No `jobserver` warnings on both s-o-g and vanilla with

```diff
--- /usr/lib/python3.9/site-packages/sage_docbuild/__init__.py.orig     2021-11-23 21:51:08.000000000 -0700
+++ /usr/lib/python3.9/site-packages/sage_docbuild/__init__.py  2021-11-23 21:27:24.000000000 -0700
@@ -262,7 +262,7 @@
         error_message = "failed to run $MAKE %s in %s"
         command = 'all-pdf'
 
-        if subprocess.call(make_target%(tex_dir, command, pdf_dir), shell=True):
+        if subprocess.call(make_target%(tex_dir, command, pdf_dir), close_fds=False, shell=True):
             raise RuntimeError(error_message%(command, tex_dir))
         logger.warning("Build finished.  The built documents can be found in %s", pdf_dir)
```
See https://stackoverflow.com/questions/29910944/is-it-possible-to-pass-through-gnu-make-jobserver-environment-to-a-submake-ser for a possible explanation. Not sure why the `False` is needed if this is the solution. If this is the fix then `sage_docbuild` will have to be patched.

**Comment by kiwifb** [comment] 2021-11-24 06:58
Looks all extremely sensible. This should be included in vanilla.

**Comment by strogdon** [comment] 2021-11-24 07:02
You check first and I'll open a trac ticket if you see things OK.

**Comment by kiwifb** [comment] 2021-11-24 08:02
I think I found a race condition _because_ parallel make now works.
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.9/site-packages/sphinx/application.py", line 343, in build
    self.builder.build_update()
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/usr/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 360, in build
    self.finish()
  File "/usr/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 652, in finish
    self.handle_finish()
  File "/usr/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1088, in handle_finish
    self.finish_tasks.add_task(self.dump_search_index)
  File "/usr/lib/python3.9/site-packages/sphinx/util/parallel.py", line 49, in add_task
    res = task_func()
  File "/usr/lib/python3.9/site-packages/sphinx/builders/html/__init__.py", line 1107, in dump_search_index
    os.replace(searchindexfn + '.tmp', searchindexfn)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/portage/sci-mathematics/sage-doc-9999/work/build_doc/html/en/website/searchindex.js.tmp' -> '/dev/shm/portage/sci-mathematics/sage-doc-9999/work/build_doc/html/en/website/searchindex.js
```
May disappear if I segregate pdf and html builds again I think.

**Comment by kiwifb** [comment] 2021-11-24 08:32
Yup, all works once I run make separately for html and pdf. Which brings us back to 17:40mn build time, slight drop compared to before figuring `jobserver` :(

But that parallel issue is separate from jobserver. It is annoying that stuff gets re-built.

**Comment by strogdon** [comment] 2021-11-24 23:35
Positive review [trac 32928](https://trac.sagemath.org/ticket/32928). If I'm not mistaken I've seen the same `FileNotFoundError`. But it was probably before `sage_docbuild` was made a spkg.

**Closed** 2022-06-28 00:11 UTC

**Comment by strogdon** [comment] 2022-06-28 00:37
The original chatter in Prefix is still present (see https://bugs.gentoo.org/826986). Probably not much we can do.

**Comment by kiwifb** [comment] 2022-06-28 00:40
That one is frustrating because the solution is known.
