### ISSUE TITLE
dev-python/pyzmq-15.2.0 fails with dev-python/cython-0.24

### ISSUE THREAD

**Issue by gagern** [cschwan/sage-on-gentoo#422] opened 2016-05-18 05:39 UTC
Emerging dev-python/pyzmq-15.2.0::gentoo fails to emerge with dev-python/cython-0.24::sage-on-gentoo:

```
cythoning zmq/backend/cython/context.pyx to zmq/backend/cython/context.c

Error compiling Cython file:
------------------------------------------------------------
...
    def underlying(self):
        """The address of the underlying libzmq context"""
        return <size_t> self.handle
    
    # backward-compat, though nobody is using it
    _handle = underlying
                       ^
------------------------------------------------------------

zmq/backend/cython/context.pyx:119:24: 'underlying' is not a constant, variable 
or function identifier
```

An issue like this has also been [reported on Ask Ubuntu](http://askubuntu.com/q/739340/71738), and the answer there indicates this to be “a bug in the development version of Cython (0.24a)”. I've not found any indication of this bug in [the Cython Trac](http://trac.cython.org/) or [the pyzmq issues list](https://github.com/zeromq/pyzmq/issues), but I might have been searching for the wrong terms.

* Do we want to mask Cython 0.24 for the time being?
* Do we want to carry this issue to either or both upstream issue trackers?

**Comment by kiwifb** [comment] 2016-05-18 07:33
Cannot mask that version of Cython, it is needed as it is for sage 7.2. Of course I cannot mask this version of pyzmq from `profile/package.mask` of the overlay. 

In the spirit of making sure we have an upstream Cython or pyzmq bug (the later one being more likely in my opinion from context) we should use a cython 0.24 that is not patched and try to reproduce first.
* if the sage patch cause problems I know who to contact to get a fix
* if the building problem persist I would put an issue to cython first

**Comment by gagern** [comment] 2016-05-18 09:18
I could reproduce using a cython 0.24 checkout. I could even bisect this to https://github.com/cython/cython/commit/9b045609cd976c1479b6f7f9fda6c742875a83ee. On the other hand, I just found that https://github.com/zeromq/pyzmq/pull/819 removed the offending line in https://github.com/zeromq/pyzmq/commit/659f9211aad1565543e26ef6877456d017c9d5bb. So the proper solution is likely to get that commit included in the ebuild.

Do you want to adopt the pyzmq package into the overlay so that we can apply that patch there? Or should I request the inclusion of this patch into the main portage tree in preparation of cython 0.24 landing there as well? Or should I just patch this locally and hope that anyone else who encounters this will find this issue here and learn how to avoid the problem?

Fortunately pyzmq supports epatch_user, so the following workaround worked for me:

```sh
mkdir -p /etc/portage/patches/dev-python/pyzmq-15.2.0
wget -O /etc/portage/patches/dev-python/pyzmq-15.2.0/659f921.patch \
  https://github.com/zeromq/pyzmq/commit/659f9211aad1565543e26ef6877456d017c9d5bb.patch
```

**Comment by kiwifb** [comment] 2016-05-18 09:51
No one has requested cython 0.24 in the main tree yet so it will be hard to get them to take the patch. Not in a timely fashion. 
epatch_user is an interesting facility if you could extend it to look at custom path aside from `/etc/portage/patches` or a place in overlays. That would avoid having to adopt an ebuild to patch it.
Just linking like for `package.accept_keywords` gets complicated very fast because of the possibility of subdirectories.

I'll adopt that ebuild with the patch in the mean time.

**Comment by juerrose** [comment] 2016-05-18 10:42
See also https://bugs.gentoo.org/show_bug.cgi?id=583192 .

**Comment by kiwifb** [comment] 2016-08-06 21:10
solved in the main tree, closing.

**Closed by kiwifb** 2016-08-06 21:10 UTC
