### ISSUE TITLE
singular fail at linking

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [cschwan/sage-on-gentoo#352] opened 2015-04-29 20:25 UTC
```
ld -shared -o p_Procs_FieldZp.sog p_Procs_Lib_FieldZp.dl_og
p_Procs_Lib_FieldZp.dl_og: In function `_omIsBinPageAddr':
/var/tmp/portage/sci-libs/libsingular-3.1.7_p1-r2/work/Singular-3-1-7/kernel/../omalloc/omalloc.h:2307: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og: In function `rField_is_Ring':
/var/tmp/portage/sci-libs/libsingular-3.1.7_p1-r2/work/Singular-3-1-7/kernel/../kernel/ring.h:161: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og: In function `rField_is_Domain':
/var/tmp/portage/sci-libs/libsingular-3.1.7_p1-r2/work/Singular-3-1-7/kernel/../kernel/ring.h:164: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og: In function `rOrd_is_Comp_dp':
/var/tmp/portage/sci-libs/libsingular-3.1.7_p1-r2/work/Singular-3-1-7/kernel/../kernel/ring.h:425: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og: In function `p_LmFree':
/var/tmp/portage/sci-libs/libsingular-3.1.7_p1-r2/work/Singular-3-1-7/kernel/../kernel/pInline2.h:316: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og:/var/tmp/portage/sci-libs/libsingular-3.1.7_p1-r2/work/Singular-3-1-7/kernel/../kernel/pInline2.h:330: more undefined references to `__stack_chk_fail_local' follow
ld: p_Procs_FieldZp.sog: hidden symbol `__stack_chk_fail_local' isn't defined
ld: final link failed: Bad value
Makefile:377: recipe for target 'p_Procs_FieldZp.sog' failed
make: *** [p_Procs_FieldZp.sog] Error 1
rm p_Procs_Lib_FieldZp.dl_og
```

see https://gist.github.com/Alessandro-Barbieri/7b3f0e04e7eb31140c80

```
emerge -pqv '=sci-libs/libsingular-3.1.7_p1-r2::sage-on-gentoo'
[ebuild  N    ] sci-libs/libsingular-3.1.7_p1-r2  USE="flint -boost -debug" 
```

**Comment by kiwifb** [comment] 2015-04-29 21:46
That's a new one. So libsingular is failing, have installed `sci-mathematics/singular` yet? It is not a dependency but that would be an interesting reference point. Also what version of gcc are you using?

**Comment by kiwifb** [comment] 2015-04-29 21:48
OK I hadn't seen `emerge --info` in the gist.

**Comment by Alessandro-Barbieri** [comment] 2015-04-29 22:00
If I try to install sci-mathematics/singular alone i get

```
i686-pc-linux-gnu-g++ -g -pipe -fno-implicit-templates -I. -I.. -I/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/build  -I/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/build/include   -Dix86_Linux -DHAVE_CONFIG_H -DDL_TAIL=\"sog\" -fpic -DPIC -Dp_Procs_FieldZp -c p_Procs_Lib.cc -o p_Procs_Lib_FieldZp.dl_og
ld -shared -o p_Procs_FieldZp.sog p_Procs_Lib_FieldZp.dl_og
p_Procs_Lib_FieldZp.dl_og: In function `_omIsBinPageAddr':
/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/kernel/../omalloc/omalloc.h:2307: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og: In function `rField_is_Ring':
/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/kernel/../kernel/ring.h:161: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og: In function `rField_is_Domain':
/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/kernel/../kernel/ring.h:164: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og: In function `rOrd_is_Comp_dp':
/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/kernel/../kernel/ring.h:425: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og: In function `p_LmFree':
/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/kernel/../kernel/pInline2.h:316: undefined reference to `__stack_chk_fail_local'
p_Procs_Lib_FieldZp.dl_og:/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/kernel/../kernel/pInline2.h:330: more undefined references to `__stack_chk_fail_local' follow
ld: p_Procs_FieldZp.sog: hidden symbol `__stack_chk_fail_local' isn't defined
ld: final link failed: Bad value
Makefile:377: recipe for target 'p_Procs_FieldZp.sog' failed
make[2]: *** [p_Procs_FieldZp.sog] Error 1
rm p_Procs_Lib_FieldZp.dl_og
make[2]: Leaving directory '/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/kernel'
Makefile:43: recipe for target 'install' failed
make[1]: *** [install] Error 1
make[1]: Leaving directory '/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7'
Makefile:29: recipe for target '/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/build/bin/Singular-3-1-7' failed
make: *** [/var/tmp/portage/sci-mathematics/singular-3.1.7_p1/work/Singular-3-1-7/build/bin/Singular-3-1-7] Error 2
```

**Comment by strogdon** [comment] 2015-04-29 23:01
Not to disrupt the flow but is it possible that
```
hidden symbol `__stack_chk_fail_local' isn't defined
```
is related to this profile
```
hardened/linux/x86/selinux
```

**Comment by kiwifb** [comment] 2015-04-29 23:07
I was in meeting so I couldn't answer but you could be right Steve. From what I can see for example here: https://github.com/dailab/libsml/issues/3 the issue is caused by the lack of stack protector and ld doesn't know about this. On x86_64 and some other archs stack protector are compulsory so it never shows but it isn't on x86. I am looking at the best way to deal with the issue.

**Comment by kiwifb** [comment] 2015-04-29 23:17
The best thing would be to use `gcc` instead of `ld` directly but that may be complicated. In the meantime adding `-fno-stack-protector` in your `C{XX}FLAGS` for both `singular` and `libsingular` will get you to compile but that's not ideal in my opinion.

**Comment by kiwifb** [comment] 2015-04-29 23:23
Hum, as another point of reference could you see if the version of `singular` from the main tree (as opposed to the overlay) will build:
```
emerge -1v --nodeps singular::gentoo
```

**Comment by Alessandro-Barbieri** [comment] 2015-04-30 00:05
Same error

**Comment by kiwifb** [comment] 2015-04-30 01:04
Thank you for trying anyway. I just committed something that I hope will solve the problem in `singular-3.1.7_p1` I would like you to sync the overlay and try to install `singular`. If it works I will mirror the fix for `libsingular`.

**Comment by Alessandro-Barbieri** [comment] 2015-04-30 15:05
Works! Thank you!

**Comment by kiwifb** [comment] 2015-04-30 21:30
OK fix mirror in `libsingular` you can sync and close the issue if things work out for you.

**Comment by Alessandro-Barbieri** [comment] 2015-05-01 15:36
Built all sage

**Closed** 2015-05-01 20:42 UTC
