### ISSUE TITLE
sage-9.6->9.7 upgrade fails...

### ISSUE THREAD

**Issue by CaptainBloodz** [cschwan/sage-on-gentoo#713] opened 2022-09-23 10:13 UTC
`     Fri Sep 23 12:52:48 2022 >>> sci-mathematics/gmp-ecm-7.0.5
     Fri Sep 23 12:54:45 2022 >>> sci-mathematics/eclib-20220621
     Fri Sep 23 12:55:33 2022 >>> dev-python/jupyter_jsmol-2022.1.0
     Fri Sep 23 12:55:51 2022 >>> sci-mathematics/sage_docbuild-9.7
     Fri Sep 23 13:02:40 2022 >>> sci-mathematics/singular-4.3.1_p1
     Fri Sep 23 13:02:59 2022 >>> sci-mathematics/sage_setup-9.7`
So far, so good...
Then 
[sci-mathematics:sage-9.7:20220923-100259.log.gz](https://github.com/cschwan/sage-on-gentoo/files/9632737/sci-mathematics.sage-9.7.20220923-100259.log.gz)
hits hard here ;).

Plz note defaulted to python3_9 here:
`eix sci-mathematics/sage
[U] sci-mathematics/sage
     Installed versions:  9.6-r1^t[1](13:37:22 19/09/2022)(X bliss doc jmol latex meataxe -debug -test PYTHON_TARGETS="python3_9 -python3_8 -python3_10")
     Homepage:            https://www.sagemath.org
     Description:         Math software for abstract and numerical computations`

**Comment by kiwifb** [comment] 2022-09-23 10:27
It looks like the previous install of sage is interfering. I recommend
```
emerge -C sage
```
before doing
```
emerge -uv sage
```
again.

**Comment by kiwifb** [comment] 2022-09-23 10:29
Just to explain, the cause of problem is
```
ImportError: cannot import name 'cython_namespace_package_support' from 'sage.misc.package_dir' (/usr/lib/python3.9/site-packages/sage/misc/package_dir.py)
```
and you'll notice that it tries to import from a system installed sage when it should do it from the source. In fact upstream may be interested in that one because it may say something about incremental updates.

**Comment by CaptainBloodz** [comment] 2022-09-23 12:03
> 



> It looks like the previous install of sage is interfering. I recommend
> 
> ```
> emerge -C sage
> ```
> 
> before doing
> 
> ```
> emerge -uv sage
> ```
> 
> again.

Problem solved.
Nice.

**Comment by CaptainBloodz** [comment] 2022-09-23 12:06
> usr/l
Planning to report upstream once everything done here.
I might have a minor one for this repository too.

**Comment by CaptainBloodz** [comment] 2022-09-23 19:21
> Just to explain, the cause of problem is
> 
> ```
> ImportError: cannot import name 'cython_namespace_package_support' from 'sage.misc.package_dir' (/usr/lib/python3.9/site-packages/sage/misc/package_dir.py)
> ```
> 
> and you'll notice that it tries to import from a system installed sage when it should do it from the source. In fact upstream may be interested in that one because it may say something about incremental updates.

Planning to report upstream once everything done here.
I might have a minor one for this repository too.

**Comment by CaptainBloodz** [comment] 2022-09-23 19:25
sage-9.7  installed fine as:
`[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sci-mathematics/sage-9.7:
 U I
 - - X                         : Add support for X11
 - - bliss                     : build the bindings to the bliss library 
 - - debug                     : Enable extra debug codepaths, like asserts
                                 and extra output. If you want to get
                                 meaningful backtraces see https://wiki.gentoo
                                 .org/wiki/Project:Quality_Assurance/Backtrace
                                 s
 - - doc                       : Add extra documentation (API, Javadoc, etc).
                                 It is recommended to enable per package
                                 instead of globally
 - - jmol                      : Make jmol the default 3D rendering engine.
                                 Tachyon will be used otherwise. 
 - - latex                     : Add support for LaTeX (typesetting package)
 - - meataxe                   : build the bindings to the shared_meataxe
                                 library 
 - - python_targets_python3_10 : Build with Python 3.10
 - - python_targets_python3_8  : Build with Python 3.8
 + + python_targets_python3_9  : Build with Python 3.9
 - - test                      : Enable dependencies and/or preparations
                                 necessary to run tests (usually controlled by
                                 FEATURES=test but can be toggled
                                 independently)`
Currently testing more USE flag activation.

**Comment by CaptainBloodz** [comment] 2022-09-24 09:31
USE=lates is fine here.
However USE=bliss fails here:

[sci-mathematics:sage-9.7:20220924-060856.log.gz](https://github.com/cschwan/sage-on-gentoo/files/9638375/sci-mathematics.sage-9.7.20220924-060856.log.gz)
Currently testing USE=meataxe.

**Comment by kiwifb** [comment] 2022-09-24 09:34
yes latest bliss is broken I believe. 0.73 should be fine but 0.77 is not. meataxe has been specifically fixed in this release see #709.

**Comment by CaptainBloodz** [comment] 2022-09-24 09:46
At least sage-9.6 builds fine with sci-libs/bliss-0.77.
Can't tell if operational though...

If that is so, maybe a version dependency constain would help.

**Comment by kiwifb** [comment] 2022-09-24 09:48
I may have a look on it tomorrow. I have been very busy with my paid work the last few months.

**Comment by kiwifb** [comment] 2022-09-30 08:06
`bliss` dependency is now constrained on 9.7 by a5496904cdb2bbf80852bc4a75177f66abd798d3. Pushed to both 9.7 and 9999 on the merge of the dev branch for the release of 9.8.beta1.

**Comment by kiwifb** [comment] 2022-09-30 08:08
I also have a patch to support sphinx 5.2 in the wing and that should be merged soon. we (sage-on-gento and arch) are pushing for 5.2.x in sage 9.8.

**Closed** 2023-12-20 00:39 UTC
